# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c1f9392f5386f311a5fbb18c96398cbae16d6d5b9846eef1c57a3d4a96598f6b018fbc7d154ce217be7efae8cf69b5f90da72ae5196661ef76f29707a340d7c

test:
  secret_key_base: bc54ae982226c1f279e759026a120dd3ea380a670cbcdd518b16d8c5e1cdc7d94c7da7716a123aa25d5517fc09392f99dd9dcef51b1ff88aa82b655d34ca4d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
